# -*- coding: utf-8 -*-
"""text-classification/Deberta-large-mnli

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlItcXLMWtjbnvl6iwib-v-lTVkMhDM6
"""

# %%
!pip install -U transformers

# %%[markdown]
"""Model page: https://huggingface.co/microsoft/deberta-large-mnli

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/microsoft/deberta-large-mnli)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

# %%
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification", model="ChrisLiewJY/BERTweet-Hedge")

# %%
import pandas as pd

df = pd.read_csv('pt_preds_fp.txt')
inputs = df['candidate_criteria_text']
res = pipe(inputs.to_list(), batch_size=16, truncation=True, max_length=120)

res

# %%
df['hedging'] = [True if e['label'] == 'LABEL_1' else False for e in res]
df['score'] = [e['score'] for e in res]
df.head()

df
